[containers.elixir]
description = "Dynamic, functional language designed for building maintainable applications"
commands = ["elixir", "mix", "iex"]
workdir = "/app"
volumes = [".:/app"]

[containers.terraform]
description = "Infrastructure as Code tool"
commands = ["terraform"]
workdir = "/workspace"
volumes = [".:/workspace"]

[containers.node]
description = "JavaScript runtime"
commands = ["node", "npm", "npx"]
workdir = "/app"
volumes = [".:/app"]

[containers.python]
description = "Python programming language"
commands = ["python", "pip"]
workdir = "/app"
volumes = [".:/app"]

[containers.gleam]
description = "A friendly language for building type-safe, scalable systems"
commands = ["gleam"]
workdir = "/app"
volumes = [".:/app"]

[containers.deno]
description = "A modern runtime for JavaScript and TypeScript"
commands = ["deno"]
workdir = "/app"
volumes = [".:/app"]

[containers.rust]
description = "A systems programming language focused on speed, memory safety, and parallelism"
commands = ["rustc", "cargo"]
workdir = "/app"
volumes = [".:/app"]