[packages.jq]
repo = "jqlang/jq"
description = "Command-line JSON processor"

[packages.jq.binaries]
names = ["jq"]

[packages.jq.urls]
linux-amd64 = "https://github.com/jqlang/jq/releases/download/jq-{version}/jq-linux-amd64"

[packages.lazydocker]
repo = "jesseduffield/lazydocker"
description = "Terminal UI for Docker and docker-compose"

[packages.lazydocker.binaries]
names = ["lazydocker"]

[packages.lazydocker.urls]
linux-amd64 = "https://github.com/jesseduffield/lazydocker/releases/download/v{version}/lazydocker_{version}_Linux_x86_64.tar.gz"
linux-arm64 = "https://github.com/jesseduffield/lazydocker/releases/download/v{version}/lazydocker_{version}_Linux_arm64.tar.gz"
darwin-amd64 = "https://github.com/jesseduffield/lazydocker/releases/download/v{version}/lazydocker_{version}_Darwin_x86_64.tar.gz"
darwin-arm64 = "https://github.com/jesseduffield/lazydocker/releases/download/v{version}/lazydocker_{version}_Darwin_arm64.tar.gz"

[packages.bat]
repo = "sharkdp/bat"
description = "Cat with syntax highlighting"

[packages.bat.binaries]
names = ["bat"]

[packages.bat.urls]
linux-amd64 = "https://github.com/sharkdp/bat/releases/download/v{version}/bat-v{version}-x86_64-unknown-linux-musl.tar.gz"
darwin-amd64 = "https://github.com/sharkdp/bat/releases/download/v{version}/bat-v{version}-x86_64-apple-darwin.tar.gz"

[packages.jj]
repo = "jj-vcs/jj"
description = "A Git-compatible VCS that is both simple and powerful "

[packages.jj.binaries]
names = ["jj"]

[packages.jj.urls]
linux-amd64 = "https://github.com/jj-vcs/jj/releases/download/v{version}/jj-v{version}-x86_64-unknown-linux-musl.tar.gz"
